import { getTranslations, setRequestLocale } from "next-intl/server";
import QRCode from "qrcode";
import { requireRole, STAFF_ROLES } from "@/lib/rbac";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { CardsToolbar } from "./cards-toolbar";
import { ShareCardButton } from "./share-card-button";
import { displayName } from "@/lib/names";

/**
 * Printable QR cards, one per active student.
 *
 * The QR encodes the student's `qrToken`, never the row id — a card can be
 * reissued by rotating the token without touching any history, and a card
 * found on the floor reveals nothing about the database.
 */
export default async function QrCardsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  await requireRole(locale, STAFF_ROLES);

  const t = await getTranslations("checkin");

  const [students, settingsRows] = await Promise.all([
    db.student.findMany({
      where: { active: true },
      orderBy: { name: "asc" },
      select: {
        id: true,
        name: true,
        qrToken: true,
        phone: true,
        guardian: { select: { phone: true } },
        gradeLevel: { select: { nameAr: true, nameEn: true } },
      },
    }),
    db.setting.findMany({ where: { key: "centerName" } }),
  ]);
  const centerName = settingsRows[0]?.value ?? "";

  // Render server-side so the page needs no client QR library.
  const cards = await Promise.all(
    students
      .filter((s) => s.qrToken)
      .map(async (s) => ({
        id: s.id,
        name: displayName(s, locale),
        // Prefer the guardian's number — the parent is who keeps the card safe.
        phone: s.guardian?.phone ?? s.phone ?? null,
        level: s.gradeLevel ? (locale === "ar" ? s.gradeLevel.nameAr : s.gradeLevel.nameEn) : "",
        token: s.qrToken!,
        svg: await QRCode.toString(s.qrToken!, {
          type: "svg",
          margin: 0,
          errorCorrectionLevel: "M",
        }),
      })),
  );

  const missing = students.length - cards.length;

  return (
    <div>
      <div className="no-print">
        <PageHeader title={t("cardsTitle")} description={t("cardsSubtitle")} />
      </div>

      <CardsToolbar missing={missing} />

      <div
        data-print="A4"
        className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 print:grid-cols-3"
      >
        {cards.map((c) => (
          <div
            key={c.id}
            className="flex break-inside-avoid flex-col items-center gap-1 rounded-lg border border-border bg-card p-3 text-center"
          >
            <div className="text-xs text-muted-foreground">{centerName}</div>
            <div
              className="w-full max-w-32 [&>svg]:h-auto [&>svg]:w-full"
              // Generated by the qrcode package from our own token — no user input.
              dangerouslySetInnerHTML={{ __html: c.svg }}
            />
            <div className="mt-1 truncate text-sm font-semibold">{c.name}</div>
            {c.level && <div className="text-xs text-muted-foreground">{c.level}</div>}
            {/* Printed so a damaged code can still be typed in manually. */}
            <div className="text-[10px] tracking-wider text-muted-foreground" dir="ltr">
              {c.token}
            </div>
            <ShareCardButton name={c.name} token={c.token} phone={c.phone} />
          </div>
        ))}
      </div>

      {cards.length === 0 && (
        <p className="rounded-lg border border-border bg-card p-8 text-center text-sm text-muted-foreground">
          {t("noCards")}
        </p>
      )}
    </div>
  );
}
